### Imports

In [70]:
import numpy as np

### Setup

In [71]:
strtoint = {
    'A':0,
    'B':1,
    'C':2,
    'D':3,
    'E':4,
    'F':5,
    'G':6,
    'H':7,
    'I':8,
    'J':9,
    'K':10,
    'L':11,
    'M':12,
    'N':13,
    'O':14,
    'P':15,
    'Q':16,
    'R':17,
    'S':18,
    'T':19,
    'U':20,
    'V':21,
    'W':22,
    'X':23,
    'Y':24,
    'Z':25,
}
intostr = {v:k for k,v in strtoint.items()}

## Encryption

### Take input for cipher key and plaintext

In [98]:
# cipher_key_str = input("Enter the key: ").upper()
# plaintext_str = input("Enter the plaintext: ").upper()
cipher_key_str = 'GYBNQKURP'
plaintext_str = 'ACT'

In [73]:
def str_to_int(str_inp):
    out_list = []
    for el in str_inp:
        out_list.append(strtoint[el])
    return out_list

In [80]:
def int_to_str(int_inp):
    out_list = []
    for el in int_inp:
        out_list.append(intostr[el])
    return out_list

In [78]:
cipher_key = str_to_int(cipher_key_str)
plaintext = str_to_int(plaintext_str)
print(f'{cipher_key=}\n{plaintext=}')

cipher_key=[6, 24, 1, 13, 16, 10, 20, 17, 15]
plaintext=[0, 2, 19]


In [79]:
# cipher_key = []
# for el in cipher_key_str:
#     cipher_key.append(stoi[el])
# plaintext = []
# for el in plaintext_str:
#     plaintext.append(stoi[el])
# print(f'{cipher_key=}\n{plaintext=}')


Finding out the matrix size

In [38]:
# matrix_size = 0
# key_len = len(cipher_key)
# print(f'{key_len=}')
# for i in range(1,len(cipher_key)//2):
#     if(key_len%i==0):
#         matrix_size = i
# print(f'{matrix_size=}')

key_len=9
matrix_size=3


In [85]:
def matrix_size_finder(cipher_key):
    matrix_size = 0
    key_len = len(cipher_key)
    print(f'{key_len=}')
    for i in range(1,len(cipher_key)//2):
        if(key_len%i==0):
            matrix_size = i
    print(f'{matrix_size=}')
    return matrix_size

In [89]:
matrix_size = matrix_size_finder(cipher_key)
matrix_size

key_len=9
matrix_size=3


3

In [39]:
# arr = []
# last_idx = 0
# for i in range(matrix_size):
#     temp = []
#     for j in range(matrix_size):
#         temp.append(cipher_key[last_idx+j])
#     last_idx = (i+1)*matrix_size
#     arr.append(temp)
# arr

[[6, 24, 1], [13, 16, 10], [20, 17, 15]]

In [88]:
def matrix_build(cipher_key,matrix_size):
    arr = []
    last_idx = 0
    for i in range(matrix_size):
        temp = []
        for j in range(matrix_size):
            temp.append(cipher_key[last_idx+j])
        last_idx = (i+1)*matrix_size
        arr.append(temp)
    return arr

In [91]:
arr = matrix_build(cipher_key,matrix_size)
arr

[[6, 24, 1], [13, 16, 10], [20, 17, 15]]

In [45]:
key_matrix = np.array(arr)
plaintext_matrix = np.array(plaintext)
print(f'{key_matrix=}\n{plaintext_matrix=}')

key_matrix=array([[ 6, 24,  1],
       [13, 16, 10],
       [20, 17, 15]])
plaintext_matrix=array([ 0,  2, 19])


In [94]:
cipher_text = key_matrix @ plaintext_matrix
cipher_text

array([ 67, 222, 319])

In [96]:
cipher_text_str = []
for i in range(len(cipher_text)):
    cipher_text[i] = cipher_text[i] % 26
    cipher_text_str.append(cipher_text[i])
cipher_text_str = ''.join(int_to_str(cipher_text_str))
cipher_text_str

'POH'

In [102]:
def encrypt(cipher_key_str,plaintext_str):
    # Converting from string to int
    cipher_key = str_to_int(cipher_key_str)
    plaintext = str_to_int(plaintext_str)
    
    #finding matrix size
    matrix_size = matrix_size_finder(cipher_key)
    # building the matrix as we want it
    arr = matrix_build(cipher_key,matrix_size)
    key_matrix = np.array(arr)
    plaintext_matrix = np.array(plaintext)

    # Getting our cipher text
    cipher_text = key_matrix @ plaintext_matrix

    cipher_text_str = []
    for i in range(len(cipher_text)):
        cipher_text[i] = cipher_text[i] % 26
        cipher_text_str.append(cipher_text[i])
    cipher_text_str = ''.join(int_to_str(cipher_text_str))

    return cipher_text_str

In [103]:
print(encrypt(cipher_key_str,plaintext_str))

key_len=9
matrix_size=3
POH


## Decryption

In [107]:
def mod_inverse(a, m):
    # Find the modular inverse of 'a' modulo 'm'
    for i in range(1, m):
        if (a * i) % m == 1:
            return i
    raise ValueError("Modular inverse does not exist")

In [108]:
def hill_cipher_inverse(matrix, modulus):
    det = int(round(np.linalg.det(matrix))) % modulus
    det_inv = mod_inverse(det, modulus)
    adjugate_matrix = np.round(det_inv * np.linalg.inv(matrix)).astype(int) % modulus
    return adjugate_matrix


In [125]:
def decryption(ciphertext_str,cipher_key_str):
    #Converting to int
    cipher_key = str_to_int(cipher_key_str)
    cipher_text = str_to_int(ciphertext_str)

    #finding matrix size
    matrix_size = matrix_size_finder(cipher_key)
    # building the matrix as we want it
    arr = matrix_build(cipher_key,matrix_size)
    key_matrix = np.array(arr)
    ciphertext_matrix = np.array(cipher_text)

    # invert the key matrix
    inv_key_matrix = hill_cipher_inverse(key_matrix,26)
    
    # getting plaintext
    plain_text = key_matrix @ plaintext_matrix

    print(plain_text)
    plain_text_str = []
    for i in range(len(plain_text)):
        plain_text[i] = plain_text[i] % 26
        plain_text_str.append(plain_text[i])
    # print(plain_text_str)
    plain_text_str = ''.join(int_to_str(plain_text_str))

    return plaintext_str
    




In [126]:
decryption('POH','GYBNQKURP')

key_len=9
matrix_size=3
[ 67 222 319]
[15, 14, 7]


'ACT'

In [105]:
test_arr = np.array([[6,24,1],[13,16,10],[20,17,15]])

In [106]:
np.linalg.(test_arr)

array([[ 0.15873016, -0.77777778,  0.50793651],
       [ 0.01133787,  0.15873016, -0.10657596],
       [-0.2244898 ,  0.85714286, -0.48979592]])